export const MOCK_PRODUCTS = [
  {
    id: "p1",
    name: "진라면 매운맛 5입",
    price: 3980,
    thumbnails: "/images/products/jin_red.jpg",
    category: "ramen",
    isNew: false,
    isBest: true,
    explanation: "국물이 끝내주는 국민 라면",
  },
  {
    id: "p2",
    name: "진라면 순한맛 5입",
    price: 3980,
    thumbnails: "/images/products/jin_blue.jpg",
    category: "ramen",
    isNew: false,
    isBest: false,
    explanation: "아이들도 좋아하는 담백한 맛",
  },
  {
    id: "p3",
    name: "오뚜기 컵밥 톡톡김치알밥",
    price: 4500,
    thumbnails: "/images/products/cup_kimchi.jpg",
    category: "instant",
    isNew: true,
    isBest: true,
    explanation: "입안에서 톡톡 터지는 식감",
  },
  {
    id: "p4",
    name: "오뚜기 컵밥 똠양꿍밥",
    price: 4800,
    thumbnails: "/images/products/cup_tomyam.jpg",
    category: "instant",
    isNew: true,
    isBest: false,
    explanation: "태국의 맛을 집에서 간편하게",
  },
  {
    id: "p5",
    name: "고소한 참기름 500ml",
    price: 12800,
    thumbnails: "/images/products/oil_gold.jpg",
    category: "oil",
    isNew: false,
    isBest: true,
    explanation: "방앗간에서 짠 듯한 고소함",
  },
  {
    id: "p6",
    name: "오뚜기 3분 카레 매운맛",
    price: 1800,
    thumbnails: "/images/products/curry_3min.jpg",
    category: "instant",
    isNew: false,
    isBest: true,
    explanation: "3분이면 완성되는 정통 카레",
  },
  {
    id: "p7",
    name: "가뿐한끼 곤약볶음밥",
    price: 3500,
    thumbnails: "/images/products/diet_rice.jpg",
    category: "instant",
    isNew: true,
    isBest: false,
    explanation: "칼로리 걱정 없는 가벼운 한 끼",
  },
  {
    id: "p8",
    name: "오뚜기 케챂 500g",
    price: 3200,
    thumbnails: "/images/products/ketchup.jpg",
    category: "sauce",
    isNew: false,
    isBest: true,
    explanation: "대한민국 No.1 토마토 케챂",
  },
  {
    id: "p9",
    name: "제주담음 제주감귤드레싱",
    price: 5900,
    thumbnails: "/images/products/jeju_dressing.jpg",
    category: "sauce",
    isNew: true,
    isBest: false,
    explanation: "제주의 싱그러움을 담은 드레싱",
  },
  {
    id: "p10",
    name: "오뚜기 미역 100g",
    price: 4200,
    thumbnails: "/images/products/seaweed.jpg",
    category: "etc",
    isNew: false,
    isBest: false,
    explanation: "부드럽고 쫄깃한 엄선된 미역",
  },
];
